# Generated by Django 3.2.11 on 2022-01-31 05:26

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.ImageField(blank=True, max_length=254, null=True, upload_to=music.models.albumFile)),
            ],
            options={
                'db_table': 'album',
            },
        ),
    ]
