# Generated by Django 3.2.11 on 2022-01-31 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'hero',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='album_hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_hero', to='music.albumhero'),
        ),
    ]
