# Generated by Django 3.2.11 on 2022-02-16 11:41

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_audios_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFavSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('track', models.FileField(upload_to='fav_songs')),
                ('duration', models.CharField(max_length=30)),
                ('album', models.ImageField(max_length=254, upload_to=music.models.fav_songs)),
            ],
        ),
    ]
