# Generated by Django 3.2.11 on 2022-02-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_addfavsongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfavsongs',
            name='hero',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
