# Generated by Django 3.2.11 on 2022-02-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_addfavsongs_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddFavSongs',
        ),
    ]
