# Generated by Django 3.2.11 on 2022-02-23 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0007_delete_addfavsongs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFavSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('track', models.FileField(upload_to='fav_songs')),
                ('duration', models.CharField(max_length=30)),
                ('album', models.ImageField(max_length=254, upload_to=music.models.fav_songs)),
                ('hero', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
