# Generated by Django 3.2.11 on 2022-04-13 09:48

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_addfavsongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumhero',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=music.models.herofile),
        ),
    ]
