# Generated by Django 3.2.11 on 2022-04-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_albumhero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumhero',
            name='image',
        ),
    ]
