# Generated by Django 3.2.11 on 2022-04-13 11:32

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_albumhero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=music.models.albumFile),
        ),
    ]
