# Generated by Django 3.2.11 on 2022-04-13 11:33

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_album_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='albumhero',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=music.models.herofile),
        ),
    ]
