# Generated by Django 3.2.11 on 2022-04-13 11:40

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20220413_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=music.models.herofile)),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.RemoveField(
            model_name='albumhero',
            name='image',
        ),
    ]
