# Generated by Django 3.2.11 on 2022-04-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_hero_hero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Actor',
        ),
    ]
