# Generated by Django 3.2.11 on 2022-04-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_rename_hero_actor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
