# Generated by Django 3.2.11 on 2022-04-14 06:52

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_delete_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=music.models.herofile)),
            ],
            options={
                'db_table': 'actor',
            },
        ),
    ]
