# Generated by Django 3.2.11 on 2022-01-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_products'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table='Users',
        ),
    ]
