# Generated by Django 3.2.11 on 2022-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userdata_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='unique_user_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
