# Generated by Django 3.2.11 on 2022-10-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userdata_unique_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='forgot_password_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
