# Generated by Django 3.2.11 on 2022-06-16 09:19

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, unique=True)),
                ('category_image', models.ImageField(blank=True, max_length=254, null=True, upload_to=food.models.foodcatFile)),
                ('discount', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'FoodCategory',
            },
        ),
    ]
