# Generated by Django 3.2.11 on 2022-06-16 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_addfoodmodel_restaurentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurentmodel',
            name='food_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.foodcategory'),
        ),
        migrations.AlterField(
            model_name='addfoodmodel',
            name='rname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.restaurentmodel'),
        ),
    ]
