# Generated by Django 3.2.11 on 2022-06-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20220616_2357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddFoodModel',
            new_name='FoodModel',
        ),
    ]
