# Generated by Django 3.2.11 on 2022-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20220716_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='fid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurentmodel',
            name='rest_id',
            field=models.CharField(max_length=30),
        ),
    ]
