# Generated by Django 3.2.11 on 2022-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_restaurentmodel_rest_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurentmodel',
            name='created_by',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
