# Generated by Django 3.2.11 on 2022-07-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_restaurentmodel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurentmodel',
            name='food_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurent', to='food.foodcategory'),
        ),
    ]
