# Generated by Django 3.2.11 on 2022-08-06 17:47

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_restaurentmodel_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurentmodel',
            name='rest_image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=food.models.restaurent_iamge),
        ),
    ]
