# Generated by Django 3.2.11 on 2022-09-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_alter_restaurentmodel_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurentmodel',
            name='food_category',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
