# Generated by Django 3.2.11 on 2022-09-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_alter_restaurentmodel_food_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodModel',
        ),
    ]
