# Generated by Django 3.2.11 on 2022-09-27 12:49

from django.db import migrations, models
import django.db.models.deletion
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_delete_foodmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=50)),
                ('restaurent_name', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=40)),
                ('item_type', models.CharField(max_length=19)),
                ('item_price', models.CharField(max_length=20)),
                ('status', models.CharField(default='available', max_length=20)),
                ('image', models.FileField(null=True, upload_to=food.models.food_item_image)),
                ('item_ratings', models.CharField(max_length=10)),
                ('food_item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_item', to='food.foodcategory')),
            ],
            options={
                'db_table': 'FoodItems',
            },
        ),
    ]
