# Generated by Django 3.2.11 on 2022-09-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_alter_itemfoodmodel_food_item_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemFoodModel',
            new_name='ItemFood',
        ),
    ]
