# Generated by Django 3.2.11 on 2022-09-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_rename_itemfoodmodel_itemfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfood',
            name='food_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.foodcategory'),
        ),
    ]
