# Generated by Django 3.2.11 on 2022-10-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_alter_itemfood_food_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfood',
            name='food_item_category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
