# Generated by Django 3.2.11 on 2022-10-14 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0026_foodcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.itemfood'),
        ),
    ]
