# Generated by Django 3.2.11 on 2022-10-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0028_auto_20221014_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfood',
            name='restaurent_name',
        ),
        migrations.AddField(
            model_name='itemfood',
            name='restaurent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.restaurentmodel'),
        ),
    ]
