# Generated by Django 3.2.11 on 2022-10-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0029_auto_20221014_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfood',
            name='restaurent',
        ),
        migrations.AddField(
            model_name='itemfood',
            name='restaurent_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
