# Generated by Django 3.2.11 on 2022-01-27 11:34

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=150, unique=True)),
                ('price', models.FloatField()),
                ('product_image', models.ImageField(blank=True, max_length=254, null=True, upload_to=products.models.productFile)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
