# Generated by Django 3.2.11 on 2022-05-04 12:04

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_cloths'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=products.models.catFile),
        ),
    ]
