# Generated by Django 3.2.11 on 2022-05-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_addtocart_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
