# Generated by Django 3.2.11 on 2022-05-27 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_addtocart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloths',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=56)),
                ('street_or_landmark', models.CharField(blank=True, max_length=56)),
                ('city', models.CharField(blank=True, max_length=56)),
                ('state', models.CharField(blank=True, max_length=56)),
                ('postal_code', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ShippingAddress',
            },
        ),
    ]
