# Generated by Django 3.2.11 on 2022-05-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='shipping',
        ),
    ]
